name: AltTeam
description: "AltAmino Control Panel for Developers and Volunteers."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.0
  
  # state management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # navigation
  go_router: ^14.2.7

  # network
  dio: ^5.4.3
  crypto: ^3.0.3

  # storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  # utils
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true

  windows:
    generate: true
    image_path: "assets/icon/icon.png"

  linux:
    generate: true
    image_path: "assets/icon/icon.png"

  macos:
    generate: true
    image_path: "assets/icon/icon.png"

  image_path: "assets/icon/icon.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/translations/